
export const TRIP_REQUEST = 'TRIP_REQUEST';
export const TRIP_SUCCESS ='TRIP_SUCCESS';
export const TRIP_ERROR = 'TRIP_ERROR';


/////old 
export const BOOKING_LIST_SUCCESS ='BOOKING_LIST_SUCCESS';
export const BOOKING_PAYMENT_LIST_SUCCESS ='BOOKING_PAYMENT_LIST_SUCCESS';
export const BOOKING_LIST_ERROR = 'BOOKING_LIST_ERROR';
export const BOOKING_LIST_REQUEST = 'BOOKING_LIST_REQUEST';
export const BOOKING_DETAIL_SUCCESS = 'BOOKING_DETAIL_SUCCESS';

export const BOOKING_DETAIL_ERROR='BOOKING_DETAIL_ERROR';
