export const MESSAGE_LIST_SUCCESS ='MESSAGE_LIST_SUCCESS';
export const MESSAGE_LIST_ERROR = 'MESSAGE_LIST_ERROR';
export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST';
export const MESSAGE_DETAIL_SUCCESS = 'MESSAGE_DETAIL_SUCCESS';