const TAG = 'USER_'

export const LOGINUSER_SUCCESS = TAG + 'LOGINUSER_SUCCESS';
export const LOGINUSER_ERROR = TAG + 'LOGINUSER_ERROR';

export const FORGOT_PASSWORD_SUCCESS = TAG + 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = TAG + 'FORGOT_PASSWORD_ERROR';

export const CHANGE_PASSWORD_SUCCESS = TAG + 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = TAG + 'CHANGE_PASSWORD_ERROR';

export const LOGOUTUSER_SUCCESS = TAG + 'LOGOUTUSER_SUCCESS';
export const LOGOUTUSER_ERROR = TAG + 'LOGOUTUSER_ERROR';

export const SIGNUP_SUCCESS = TAG + 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = TAG + 'SIGNUP_ERROR';

export const GETPROFILE_SUCCESS = TAG + 'GETPROFILE_SUCCESS';
export const GETPROFILE_ERROR = TAG + 'GETPROFILE_ERROR';

export const UPDATEPROFILE_SUCCESS = TAG + 'UPDATEPROFILE_SUCCESS';
export const UPDATEPROFILE_ERROR = TAG + 'UPDATEPROFILE_ERROR';

export const GET_GALLERY_SUCCESS = TAG + 'GET_GALLERY_SUCCESS';
export const GET_GALLERY_ERROR = TAG + 'GET_GALLERY_ERROR';

export const STORE_GALLERY_IMAGE_SUCCESS = TAG + 'STORE_GALLERY_IMAGE_SUCCESS';
export const STORE_GALLERY_IMAGE_ERROR = TAG + 'STORE_GALLERY_IMAGE_ERROR';

export const DELETE_GALLERY_IMAGE_SUCCESS = TAG + 'DELETE_GALLERY_IMAGE_SUCCESS';
export const DELETE_GALLERY_IMAGE_ERROR = TAG + 'DELETE_GALLERY_IMAGE_ERROR';

export const GET_DOCUMENT_SUCCESS = TAG + 'GET_DOCUMENT_SUCCESS';
export const GET_DOCUMENT_ERROR = TAG + 'GET_DOCUMENT_ERROR';

export const DOCUMENT_STORE_SUCCESS = TAG + 'DOCUMENT_STORE_SUCCESS';
export const DOCUMENT_STORE_ERROR = TAG + 'DOCUMENT_STORE_ERROR';




