const TAG = 'CONTENT_'

export const CMS_PAGE_SUCCESS = TAG + 'CM_S_PAGE_SUCCESS';
export const CMS_PAGE_ERROR = TAG + 'CMS_PAGE_ERROR';
export const FAQLIST_SUCCESS = TAG + 'FAQLIST_SUCCESS';
export const FAQLIST_ERROR = TAG + 'FAQLIST_ERROR';
export const FAQDETAILS_SUCCESS = TAG + 'FAQDETAILS_SUCCESS';
export const FAQDETAILS_ERROR = TAG + 'FAQDETAILS_ERROR';
